### ISSUE TITLE
Generate swift package dependencies from YAML file

### ISSUE THREAD

**Issue by cgrindel** [cgrindel/spm_bazel#4]
## Goals
Add `generate` command:
  1. Reads YAML file describing direct dependencies. (Similar to Swift package manifest syntax).
  2. Create a Swift package manifest.
  3. Fetch the transitive dependencies using the manifest.
  4. Generate Bazel workspace rules and `BUILD.bazel` files for the transitive deps.
  5. Write the results to spm_deps.bzl

## Tasks
- [x] #5 
- [ ] Read a YAML file with dependencies.
- [ ] Generate a Swift package manifest and fetch the transitive dependencies.
- [ ] Write the results to `spm_deps.bzl`.
